language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
services:
  - mongodb
before_script:
  - mongo kigc-blog-test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm install
  - npm test
after_success:
  - npm run coverage
